In [1]:
import pandas as pd
import numpy as np
print('librerias importadas')

librerias importadas

In [2]:
dataset = pd.read_csv('./B&F_transformado.csv')

In [3]:
seleccion = dataset.groupby(['Location','Month', 'Day_Type', 'Day']).Total.count().reset_index()

In [4]:
location = seleccion['Location'].unique()
meses = seleccion['Month'].unique()
tipo_dia = seleccion['Day_Type'].unique()

In [5]:
#Filtrado de elementos del data set por medio de tiendas
ubicaciones = [seleccion[seleccion['Location']==tienda] for tienda in location]
#filtrado de las Tiendas por mes
Meses = [ubicacion[ubicacion['Month']==mes] for mes in meses for ubicacion in ubicaciones]

#Filtrado de los meses por tipo "entre semana" o "fin de semana"
Dias = []
for mes in Meses:
    if len(mes) > 0:
        for tipo in tipo_dia:
            Dias.append(mes[mes['Day_Type']==tipo])

In [6]:
top_days =[]
for Tipo in Dias:
    Tipo = Tipo.sort_values(by='Total', ascending = False)
    top_days.append(Tipo.head(1))

In [7]:
Top = pd.concat(top_days)
Top

    Location    Month       Day_Type        Day  Total
3   Tienda A    Enero   Entre Semana  Miercoles     65
5   Tienda A    Enero  Fin de Semana     Sábado    127
24  Tienda B    Enero   Entre Semana  Miercoles     34
26  Tienda B    Enero  Fin de Semana     Sábado     50
8   Tienda A  Febrero   Entre Semana      Lunes     41
12  Tienda A  Febrero  Fin de Semana     Sábado     99
29  Tienda B  Febrero   Entre Semana      Lunes     34
33  Tienda B  Febrero  Fin de Semana     Sábado     55
43  Tienda C  Febrero   Entre Semana      Lunes      8
47  Tienda C  Febrero  Fin de Semana     Sábado     16
14  Tienda A    Marzo   Entre Semana     Jueves     60
19  Tienda A    Marzo  Fin de Semana     Sábado    112
35  Tienda B    Marzo   Entre Semana     Jueves     34
40  Tienda B    Marzo  Fin de Semana     Sábado     61
49  Tienda C    Marzo   Entre Semana     Jueves     12
54  Tienda C    Marzo  Fin de Semana     Sábado     26